sequenceDiagram
    participant entrypoint_sqs_event as entrypoint:sqs_event
    participant agent_gatekeeper as agent:gatekeeper
    participant lambda_actionGroupFoo as lambda:actionGroupFoo

    entrypoint_sqs_event->>entrypoint_sqs_event: InvokeLambda [attempt 1]
    Note over entrypoint_sqs_event,entrypoint_sqs_event: req=payloads/span-001.request.json, res=payloads/span-001.response.json, λ:req-aaa

    entrypoint_sqs_event->>agent_gatekeeper: InvokeAgent [attempt 1]
    Note over entrypoint_sqs_event,agent_gatekeeper: req=payloads/span-002.request.json, res=payloads/span-002.response.json, br:sess-111

    agent_gatekeeper->>lambda_actionGroupFoo: InvokeModel [attempt 1]
    Note over agent_gatekeeper,lambda_actionGroupFoo: req=payloads/span-003.request.json, res=payloads/span-003.response.json

