# Outputs for ITK infrastructure

output "lambda_function_name" {
  description = "Name of the Lambda function"
  value       = aws_lambda_function.haiku_invoker.function_name
}

output "lambda_function_arn" {
  description = "ARN of the Lambda function"
  value       = aws_lambda_function.haiku_invoker.arn
}

output "lambda_log_group" {
  description = "CloudWatch log group for Lambda"
  value       = aws_cloudwatch_log_group.lambda.name
}

output "sqs_queue_url" {
  description = "URL of the SQS queue"
  value       = aws_sqs_queue.test_queue.url
}

output "sqs_queue_arn" {
  description = "ARN of the SQS queue"
  value       = aws_sqs_queue.test_queue.arn
}

output "supervisor_agent_id" {
  description = "ID of the supervisor Bedrock agent"
  value       = aws_bedrockagent_agent.supervisor.id
}

output "supervisor_agent_alias_id" {
  description = "Alias ID of the supervisor agent"
  value       = aws_bedrockagent_agent_alias.supervisor.agent_alias_id
}

output "worker_agent_id" {
  description = "ID of the worker Bedrock agent"
  value       = aws_bedrockagent_agent.worker.id
}

output "worker_agent_alias_id" {
  description = "Alias ID of the worker agent"
  value       = aws_bedrockagent_agent_alias.worker.agent_alias_id
}

output "env_file_content" {
  description = "Content for .env.live file"
  value       = <<-EOT
    # ITK Live Environment Configuration
    # Generated by Terraform
    
    ITK_MODE=live
    AWS_REGION=${local.region}
    AWS_PROFILE=${var.aws_profile}
    
    # Lambda
    ITK_LAMBDA_FUNCTION=${aws_lambda_function.haiku_invoker.function_name}
    ITK_LOG_GROUPS=${aws_cloudwatch_log_group.lambda.name}
    
    # SQS
    ITK_SQS_QUEUE_URL=${aws_sqs_queue.test_queue.url}
    
    # Bedrock Agents
    ITK_SUPERVISOR_AGENT_ID=${aws_bedrockagent_agent.supervisor.id}
    ITK_SUPERVISOR_ALIAS_ID=${aws_bedrockagent_agent_alias.supervisor.agent_alias_id}
    ITK_WORKER_AGENT_ID=${aws_bedrockagent_agent.worker.id}
    ITK_WORKER_ALIAS_ID=${aws_bedrockagent_agent_alias.worker.agent_alias_id}
    
    # Model
    ITK_MODEL_ID=${var.model_id}
  EOT
}
